name: deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  builds:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: fregante/setup-git-user@v1
      - name: Install dependencies
        run: npm install
      - name: deploy
        run: npm run deploy
